const countries = [
  {
    id: 0,
    name: 'ALBANIA',
    image: 'https://i2-prod.mirror.co.uk/incoming/article28374079.ece/ALTERNATES/s1200/0_Sunshade-umbrellas-deckchairs-and-boats-on-the-beautiful-Ksamil-beach-Vlore-Ionian-sea-Albania.jpg',
    description: 'Albania is a beautiful country in the Balkans known for its stunning landscapes, including mountains, beaches, and lakes. It has a rich history and offers visitors a mix of ancient ruins, Ottoman architecture, and vibrant cities like the capital, Tirana.',
  },
  {
    id: 1,
    name: 'FRANCE',
    image: 'https://www.expatica.com/app/uploads/sites/5/2014/05/Mont-Saint-Michel.jpg',
    description: 'France, the epitome of romance and culture, is famous for its world-class cuisine, iconic landmarks like the Eiffel Tower, and beautiful countryside. From the stylish streets of Paris to the picturesque vineyards of Bordeaux, France offers a diverse and captivating experience.',
  },
  {
    id: 2,
    name: 'AUSTRIA',
    image: 'https://media.cntraveler.com/photos/61237e07cdc5e31256a6bde1/16:9/w_5727,h_3221,c_limit/Austria_GettyImages-1146702072.jpg',
    description: 'Austria, located in the heart of Europe, is known for its rich history, classical music heritage, and stunning Alpine landscapes. Vienna, the capital, is renowned for its imperial palaces and cultural events, while the Austrian Alps offer excellent opportunities for outdoor enthusiasts.',
  },
  {
    id: 3,
    name: 'TURKEY',
    image: 'https://move2turkey.com/wp-content/uploads/2020/12/The-most-famous-bridges-of-Istanbul-in-Turkey3.jpg',
    description: 'Turkey bridges two continents, offering a unique blend of cultures and history. From the ancient city of Istanbul with its iconic Hagia Sophia and Blue Mosque to the otherworldly landscapes of Cappadocia, Turkey is a treasure trove of wonders waiting to be explored.',
  },
  {
    id: 4,
    name: 'GREECE',
    image: 'https://d1bv4heaa2n05k.cloudfront.net/user-images/1523266193577/shutterstock-1031949604_main_1523266204520.jpeg',
    description: 'Greece, the birthplace of Western civilization, is known for its ancient history, magnificent islands, and delectable Mediterranean cuisine. From the iconic Parthenon in Athens to the beautiful beaches of Santorini and Mykonos, Greece is a dream destination for many.',
  },
  {
    id: 5,
    name: 'SPAIN',
    image: 'https://cdn.kimkim.com/files/a/content_articles/featured_photos/9fc6e563b8ba3e78eae604da7e58d983a5294d27/big-c18195b2dfe79a520e4ec9c43832057a.jpg',
    description: 'Spain, a vibrant country in southwestern Europe, captivates visitors with its lively culture, stunning architecture, and diverse landscapes. From the historic streets of Barcelona to the sun-kissed beaches of the Costa del Sol, Spain offers something for every traveler.',
  },
  {
    id: 6,
    name: 'ITALY',
    image: 'https://media.timeout.com/images/106015066/750/562/image.jpg',
    description: 'Italy, the land of la dolce vita, is famous for its art, history, and mouthwatering cuisine. From the ancient ruins of Rome to the romantic canals of Venice and the picturesque coasts of the Amalfi and Cinque Terre, Italy is a treasure trove of cultural delights.',
  },
  {
    id: 7,
    name: 'SWEDEN',
    image: 'https://www.insightvacations.com/media/2iymomqq/sweden-guided-tours-travel-guide.jpg',
    description: 'Sweden, a Scandinavian gem, is known for its stunning landscapes, innovative design, and progressive society. From the colorful streets of Stockholm to the magical Northern Lights in Swedish Lapland, Sweden offers a unique experience for travelers.',
  },
  {
    id: 8,
    name: 'VIETNAM',
    image: 'https://img.traveltriangle.com/blog/wp-content/uploads/2017/04/shutterstock_524159674-kw-100417-A-beautiful-snap-of-the-floating-fishing-village-and-rock-island-in-Halong-Bay.jpg',
    description: 'Vietnam, located in Southeast Asia, is renowned for its rich history, delicious cuisine, and natural beauty. From the bustling streets of Hanoi to the serene waters of Ha Long Bay and the vibrant lantern-lit alleys of Hoi An, Vietnam is a country of contrasts and charm.',
  },
  {
    id: 9,
    name: 'SLOVENIA',
    image: 'https://www.schengenvisainfo.com/news/wp-content/uploads/2022/04/Ljubljana-Slovenia.jpg',
    description: 'Slovenia, a hidden gem in Central Europe, captivates visitors with its pristine nature, charming towns, and warm hospitality. From the emerald waters of Lake Bled to the vibrant capital, Ljubljana, Slovenia offers a perfect blend of adventure and relaxation.',
  },
  {
    id: 10,
    name: 'SWITZERLAND',
    image: 'https://s30876.pcdn.co/wp-content/uploads/Switzerland-e1634207571492.jpg.optimal.jpg',
    description: 'Switzerland, nestled in the heart of the Alps, is known for its breathtaking landscapes, world-class ski resorts, and Swiss precision. From the majestic Matterhorn to the charming cities of Zurich and Lucerne, Switzerland is a paradise for nature lovers and adventure seekers.',
  },
  {
    id: 11,
    name: 'CZECH REPUBLIC',
    image: 'https://localadventurer.com/wp-content/uploads/2019/08/prague-clock.jpg',
    description: 'The Czech Republic, located in Central Europe, is famous for its fairytale-like castles, historic towns, and exceptional beer. From the stunning Prague Castle to the enchanting streets of Cesky Krumlov, the Czech Republic offers a journey back in time.',
  },
  {
    id: 12,
    name: 'ROMANIA',
    image: 'https://img.theculturetrip.com/wp-content/uploads/2021/05/bran-castle.jpg',
    description: 'Romania, a country rich in history and folklore, is known for its medieval castles, lush landscapes, and traditional villages. From the majestic Bran Castle (Dracula\'s Castle) to the mystical landscapes of Transylvania, Romania is a land of legends and surprises.',
  },
  {
    id: 13,
    name: 'NETHERLANDS',
    image: 'https://img.traveltriangle.com/blog/wp-content/uploads/2017/11/Places-To-Visit-In-Netherlands_15th-jun.jpg',
    description: 'The Netherlands, also known as Holland, is famous for its picturesque windmills, tulip fields, and iconic canals. From the vibrant city of Amsterdam to the historic town of Delft, the Netherlands offers a delightful blend of culture and charm.',
  },
  {
    id: 14,
    name: 'ICELAND',
    image: 'https://traveladdicts.net/wp-content/uploads/2020/01/Godafoss-falls-in-Iceland-winter-1.jpg.webp',
    description: 'Iceland, the land of fire and ice, is renowned for its otherworldly landscapes, including glaciers, volcanoes, and geothermal springs. From the magical Northern Lights to the famous Blue Lagoon, Iceland is a nature lover\'s paradise.',
  },
  {
    id: 15,
    name: 'UNITED KINGDOM',
    image: 'https://www.travelandleisure.com/thmb/3Iul9mBZaj40HHmCaHzL6z7Y5J0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/london-cityscape-UKESSAY1222-3c3b4b23062f410080b77839b31243a6.jpg',
    description: 'The United Kingdom, composed of England, Scotland, Wales, and Northern Ireland, is known for its rich history, iconic landmarks, and diverse culture. From the historic sites of London to the stunning landscapes of Scotland\'s Highlands, the UK offers a mix of tradition and modernity.',
  },
  {
    id: 16,
    name: 'HUNGARY',
    image: 'https://ak.jogurucdn.com/media/image/media_gallery-2018-11-20-9-3_b8d47843363247fef85b5181743552fe.jpg',
    description: 'Hungary, a Central European gem, is famous for its thermal baths, vibrant capital Budapest, and rich cultural heritage. From the romantic Danube River to the fairy tale-like castles of Eger and Veszprém, Hungary is a country of both history and natural beauty.',
  },
  {
    id: 17,
    name: 'SLOVAKIA',
    image: 'https://brusselsmorning.com/wp-content/uploads/2022/11/best-places-to-visit-in-slovakia-50.jpgw3_.webp',
    description: 'Slovakia, a charming country in Central Europe, is known for its medieval towns, stunning mountains, and welcoming atmosphere. From the historic capital Bratislava to the High Tatras National Park, Slovakia offers a perfect mix of culture and outdoor adventures.',
  },
  {
    id: 18,
    name: 'POLAND',
    image: 'https://www.pacificprime.com/blog/wp-content/uploads/Poland-9-Best-Cities-For-Expats-1200x720.jpg',
    description: 'Poland, located in Eastern Europe, boasts a rich history and cultural heritage. From the medieval Old Town of Krakow to the poignant history of Auschwitz, Poland offers a mix of historical sites and natural beauty, including the scenic Tatra Mountains.',
  },
  {
    id: 19,
    name: 'NORWAY',
    image: 'https://cdn.britannica.com/64/94864-050-223C3FE6/Northern-lights-sky-Kautokeino.jpg',
    description: 'Norway, known for its dramatic fjords, pristine wilderness, and vibrant cities, is a paradise for nature enthusiasts. From the Northern Lights in Tromsø to the stunning Geirangerfjord, Norway is a land of breathtaking landscapes and outdoor adventures.',
  },
  {
    id: 20,
    name: 'PORTUGAL',
    image: 'https://fullsuitcase.com/wp-content/uploads/2020/04/Best-cities-in-Portugal.jpg.webp',
    description: 'Portugal, a country on the Iberian Peninsula, offers a blend of history, culture, and scenic beauty. From the charming streets of Lisbon to the vineyards of Porto and the stunning beaches of the Algarve, Portugal provides a diverse and rewarding travel experience.',
  },
  {
    id: 21,
    name: 'BELGIUM',
    image: 'https://www.planetware.com/wpimages/2020/02/belgium-in-pictures-beautiful-places-to-photograph-canals-bruges.jpg',
    description: 'Belgium, famous for its medieval towns, delicious chocolates, and Belgian waffles, is a hidden gem in Western Europe. From the historic city of Bruges to the vibrant capital, Brussels, Belgium offers a mix of art, history, and gastronomy.',
  },
  {
    id: 22,
    name: 'INDONESIA',
    image: 'https://www.holidify.com/images/bgImages/BALI.jpg',
    description: 'Indonesia, the world\'s largest archipelago, is known for its diverse landscapes and cultures. From the pristine beaches of Bali to the ancient temples of Borobudur and the lush jungles of Sumatra, Indonesia is a land of breathtaking beauty and cultural wonders.',
  },
  {
    id: 23,
    name: 'GERMANY',
    image: 'https://media.istockphoto.com/id/607466764/photo/cologne-at-dusk.jpg?s=612x612&w=0&k=20&c=FQqcZQbAjfYPy-QiXdeKiw2dIGGNamuSGXKqzgqqpjw=',
    description: 'Germany, with its rich history, charming villages, and modern cities, offers a delightful mix of old and new. From the iconic Brandenburg Gate in Berlin to the fairytale castles of Bavaria and the scenic Rhine Valley, Germany is a country full of surprises.',
  },
];

export default countries